### ISSUE TITLE
synthesizeSpeech very slow on RPi 3

### ISSUE THREAD

**Issue by matrixOperator** [Losant/inspiration-station#1]
Polly.synthesizeSpeech takes a long time on my Raspberry Pi 3 for the callback to trigger.
With the benchmark below (and a similar one that repeatedly tests the callback/handling),  I am getting dt ~ 300 ms on Win10 and Win7 desktops, and dt ~15000 ms on the RPi 3. This is pretty unacceptable (the TTS text was simply "Hello")!

```
console.time('dt')
Polly.synthesizeSpeech(params, (err, data) => {
      if (err) {
          console.log(err.code)
      } else if (data) {
          if (data.AudioStream instanceof Buffer) {
              console.timeEnd('dt')
          }
      }
  })
}
```

All the machines are on the same network and have similar ping times; and this happens to the RPi regardless wired or wireless connectivity. I tried doing a fresh install of Raspbian Jessie w/ Pixel on the entire 32 GB SD card, and set up with my minimum dev config:
- Node.js 7.10, Samba, RealVNC, SSH, 16 MB GPU Memory.

and tested a stripped down script with only `aws-sdk` module included. Same slow response. So I suspect it has more to do with the system configuration - since the response looks really snappy in @anaptfox's [video](https://www.losant.com/blog/speech-synthesis-on-the-raspberry-pi-using-node.js?utm_source=nodeweekly&utm_medium=email).

Tried:
 - Booting to CLI, disabling Samba, disabling swap. Still terribly slow. `top` shows swap was not even touched during the execution (when I had swap enabled), and `node` did not even exceeds 2% in CPU load while handling callbacks. 
- Changed the script so it only requires the necessary aws libs:
``import AWS = require('aws-sdk/global'); awsPolly = require('aws-sdk/clients/polly').`` Same results.
- Finally went with fresh install of Jessie Lite. Set up Wif, enabled SSH, installed node 7.10 via nvm, installed git to clone aws-nodejs-sample, npm install in the source directory. Literally no excess other than the Wifi WPA2 connection. Still the slow benchmark... :(

@anaptfox could you share with us what is your system configuration such that your response so snappy?

Thank you for the sweet tutorials!

**Comment by anaptfox** [comment]
@ddwp99 thanks for this AWESOME issue. 

I believe I ran this demo on a Raspberry Pi 2 ( with a WiFI dongle). But, I'll have access to a Pi 3 tomorrow. I'll get this running on the Pi 3 and do some testing

**Comment by matrixOperator** [comment]
Inspired by [this answer](http://stackoverflow.com/questions/30470228/slow-https-request-with-node-js-and-express-js), this [perspective (for servers)](https://www.paypal-engineering.com/2014/04/01/outbound-ssl-performance-in-node-js/), and [this AWS document](https://aws.amazon.com/blogs/aws/polly-text-to-speech-in-47-voices-and-24-languages/) ("Polly encrypts all data at rest and transfers the audio across SSL connections."):

As it turns out, the script was spending most of its time re-establishing the SSL handshake on each Polly request (As confirmed by CPU profiles sampled with Chrome DevTools). To resolve this issue, ~~we need the module _[agentkeepalive](https://www.npmjs.com/package/agentkeepalive)_~~ we use the build-in [https](https://nodejs.org/api/https.html) module. The following test code is what finally (finally!!!) worked for me:

```
const AWS = require('aws-sdk')
const httpsAgent = require('https').Agent

const keepAliveAgent = new httpsAgent({maxSockets:1, keepAlive:true})
AWS.config.update({
    httpOptions: { agent: keepAliveAgent }
})

const Polly = new AWS.Polly({
    signatureVersion: 'v4',
    region: 'us-east-1',
    logger: console
})

let params = {
    'Text': 'Hello.',
    'OutputFormat': 'mp3',
    'VoiceId': 'Kimberly'
}

speechHandler = function(err,data){
    if (err) {
        console.log(err.code)
    } else if (data) {
        if (data.AudioStream instanceof Buffer) {
            console.timeEnd('dt')
            console.time('dt')
            Polly.synthesizeSpeech(params,speechHandler)
        }
    }
}
console.time('dt')
Polly.synthesizeSpeech(params,speechHandler)
```
AWS seems to use the allotted sockets freely when you give it the option. So if ``maxSockets`` is much greater than 1,  this script may still try to negotiate with each SSL socket before finally all of them are kept alive. I had to set the property ``maxSockets'' to 1, such that the SSL _stalls_ only for the very first request. In applications, I might just execute empty requests on timed intervals to keep the SSL connection alive.

Now my RPi 3 is returning the data for the speech segment "Hello" in ~90 ms (as opposed to taking ~15000 ms before agentkeepalive)! I can finally sleep tonight. Keep in mind the first response still took ~15000 ms.
I also tried this on the Win10, which improves the duration from ~300 ms down to ~85 ms!! 

Again, seriously thanks for the tutorial. Knowing that this was possible on your RPi at one point is what kept me digging.

**Comment by ddwp99** [comment]
Just out of curiosity, @anaptfox , did you have any kind of SSL caching enabled in your original demo RPi 3 or the network? (If so...how?...it would be convenient to enable this behavior system-wide; since the AWS-CLI based on Python also seems to have the same sluggishness on my RPi.) Or do you think maybe something changed on the AWS end between then and now?
